commands:
  action:
    help: "place your actions (verbs) under action. eg, create, make, delete"
    choices:
      - create # this is an example
  object:
    help: "place here the objects (nouns) which will be acted upon. eg file, migration, table"
    choices:
      - file # this is an example
